### ISSUE TITLE
hashValues deprecated

### ISSUE THREAD

**Issue by esentis** [esentis/infinite_grouped_list#5]
The package depends on` flutter_sticky_header`, and there is currently an open [issue](https://github.com/letsar/flutter_sticky_header/issues/99) with this one.

**Comment by stan-at-work** [comment]
@esentis Fix this please

**Comment by stan-at-work** [comment]
@esentis Why did you close is it fixed ?

**Comment by esentis** [comment]
@stan-at-work Yes ! Updating the `sticky_header` to 0.7.0 both on `pubspec.yaml` and `pubspec.lock`, the error has gone.
